import 'package:flutter/material.dart';
import 'package:open_rocketry/const.dart';
import 'package:url_launcher/url_launcher.dart';

class FlightMechanics extends StatelessWidget {
  const FlightMechanics({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.red,
        title: Padding(
          padding: EdgeInsets.only(left: 20),
          child: Text(
            "HOW WILL ROCKETS FLY ??",
            style: TextStyle(fontSize: 17),
          ),
        ),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(15.0),
          child: Column(
            children: [
              Text("CHECK OUT CHAPTER 14 'LEARN IN RIGHT WAY' FIRST THEN START THIS MODULE !!",style: ktiles,),
              SizedBox(height: 15,),
              Text("In this module you will learn about aerodynamics of the spacecraft. I won't provide any explanation in this module because this topic is so huge in itself i will provide some of the best resources for learning so follow up the resources.Go through all the resources don't just see it learn different concepts explore everything you can.. you cannot complete this module in 3-4 hours it will takes days or even months to complete this module because this is the most important part without this knowledge dreaming anything about space is just useless..",style: ktimeword,),
              SizedBox(height: 10,),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Wiki SpaceFlight (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://en.wikipedia.org/wiki/Portal:Spaceflight"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Wiki Rocketry (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://en.wikipedia.org/wiki/Portal:Rocketry"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Wiki OuterSpace (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://en.wikipedia.org/wiki/Portal:Outer_space"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Basics Physics (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://www.physicsclassroom.com/class"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("MIT Aerodynamics (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://ocw.mit.edu/search/ocwsearch.htm?q=aerodynamics"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Core Books On Rocketry (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://github.com/12tilak34/Rocketry"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Advances in Aerodynamics (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://aia.springeropen.com/"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Numerical Analysis (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://en.wikipedia.org/wiki/Numerical_analysis"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Finite element method (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://en.wikipedia.org/wiki/Finite_element_method"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Mathematical Modeling (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://en.wikipedia.org/wiki/Mathematical_model"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Computational Fluid Dynamics (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://en.wikipedia.org/wiki/Computational_fluid_dynamics"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Heat Transfer (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://en.wikipedia.org/wiki/Heat_transfer"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Mathematical Fluid Dynamics (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://services.math.duke.edu/~witelski/228/#:~:text=Math%20228%3A%20Mathematical%20Fluid%20Dynamics%20(Spring%202012),mathematics%2C%20physics%2C%20and%20engineering."),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Aeroelasticity (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://en.wikipedia.org/wiki/Aeroelasticity"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Vibrations (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://en.wikipedia.org/wiki/Vibration"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Buckling (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://en.wikipedia.org/wiki/Buckling"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Intermediate Dynamics (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://www.researchgate.net/publication/265459965_Intermediate_Dynamics/link/5886b95492851c21ff4d62c5/download"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Convection Heat Transfer) (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://en.wikipedia.org/wiki/Convection_(heat_transfer)"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Compressible Flow (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://en.wikipedia.org/wiki/Compressible_flow"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Engineering Acoustics (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://en.wikipedia.org/wiki/Acoustical_engineering"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Unsteady Aerodynamics PDF (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://sci-hub.se/https://doi.org/10.1016/j.paerosci.2003.04.001"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Partial differential equation (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://en.wikipedia.org/wiki/Partial_differential_equation"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Thermodynamics (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://en.wikipedia.org/wiki/Thermodynamics"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Continuum mechanics (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://en.wikipedia.org/wiki/Continuum_mechanics"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Mathematical Optimization (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://en.wikipedia.org/wiki/Mathematical_optimization"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Numerical Linear Algebra (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://en.wikipedia.org/wiki/Numerical_linear_algebra"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Stochastic process (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://en.wikipedia.org/wiki/Stochastic_process"),),
              Text("-------------------------------------------------------------------------------------"),
              SizedBox(height: 10,),
              InkWell(child: Text("Download Research papers for free (CLICK)",style: klinkstyle,),onTap: ()=>launch("https://sci-hub.se/"),),
              SizedBox(height: 15,),
              Text("Go through every link and understand the concepts give proper timings \n \n \n                    (( ALL THE VERY BEST !! ))",style: ktimeword,),
            ],
          ),
        ),
      ),
    );
  }
}
